version: "3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: dockerfiles/api.dockerfile
    command: [ 'python', '-m' , 'flask', 'run', '--host=0.0.0.0']
    environment:
      - TZ=GMT+2
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - database
      - cache
    networks:
      - api_network
  database:
    container_name: mysql-db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - TZ=GMT+2
    env_file:
      - ./.env
    volumes:
      - ./databases/storage:/var/lib/mysql
      - ./databases/schema:/tmp/database
    command: mysqld --init-file="/tmp/database/schema.sql"
    networks:
      - api_network
  cache:
    container_name: redis-cache
    environment:
      - TZ=GMT+2
    env_file:
      - ./.env
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - api_network
networks:
  api_network:
