USE api_db;

CREATE TABLE IF NOT EXISTS `CIVILIZATION` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(45) DEFAULT NULL,
  `EXPANSION` varchar(45) DEFAULT NULL,
  `TEAM_BONUS` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `CIVILIZATION_BONUS` (
  `BONUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CIVILIZATION_ID` int(11) DEFAULT NULL,
  `BONUS_DISCRIPTION` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`BONUS_ID`),
  KEY `CIVILIZATION_ID_idx` (`CIVILIZATION_ID`),
  CONSTRAINT `CIVILIZATION_ID` FOREIGN KEY (`CIVILIZATION_ID`) REFERENCES `CIVILIZATION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
